"""create detections table

Revision ID: 780f4f290053
Revises: d04b44a7b5ca
Create Date: 2026-07-19 17:57:59.959819

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "780f4f290053"
down_revision: Union[str, Sequence[str], None] = "d04b44a7b5ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "detections",
        sa.Column("rule_name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_detections_event_id"), "detections", ["event_id"], unique=False
    )
    op.create_index(op.f("ix_detections_id"), "detections", ["id"], unique=False)
    op.create_index(
        op.f("ix_detections_rule_name"), "detections", ["rule_name"], unique=False
    )
    op.create_index(
        op.f("ix_detections_severity"), "detections", ["severity"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_detections_severity"), table_name="detections")
    op.drop_index(op.f("ix_detections_rule_name"), table_name="detections")
    op.drop_index(op.f("ix_detections_id"), table_name="detections")
    op.drop_index(op.f("ix_detections_event_id"), table_name="detections")
    op.drop_table("detections")
    # ### end Alembic commands ###
